apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: wordpress-ns
spec:
  selector:
    app: wordpress
  ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
  clusterIP: None
